# Generated by Django 3.1.7 on 2021-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
