# Generated by Django 3.1.7 on 2021-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0003_auto_20210326_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, default='', help_text='Do not fill subscription id value', max_length=250, null=True),
        ),
    ]
